repos:
  - repo: local
    hooks:
      - id: safety-check
        name: Check for package vulnerabilities
        entry: poetry run safety
        language: python
        args: [ check, --full-report, -i, '70612' ]
        additional_dependencies: [ safety ]
        pass_filenames: false

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: Sort package imports
        args: [--profile, black]
        files: ^(spark_instructor|tests)/

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: Clean code formatting
        files: ^(spark_instructor|tests)/

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        additional_dependencies: [Flake8-pyproject==1.2.3]
        args: [--config, pyproject.toml]
        name: Lint the code
        files: ^(spark_instructor|tests)/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
        name: Run static typing
        files: ^(spark_instructor|tests)/

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: Check for docstring issues
        files: ^spark_instructor/

  - repo: local
    hooks:
      - id: pytest-cov
        name: Run full coverage test suite
        entry: poetry run pytest
        language: system
        args: [--cov=spark_instructor, --cov-report, term-missing]
        pass_filenames: false
        always_run: true

default_language_version:
  python: python3

exclude: ^(.git|.tox|.venv|build|dist)/
