site_name: spark-instructor
repo_url: https://github.com/TJC-LP/spark-instructor
repo_name: TJC-LP/spark-instructor
site_author: Richie Caputo
edit_uri: ""

theme:
  name: "material"
  font:
    text: Raleway
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  icon:
    logo: material/shimmer
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav:
  - Home: index.md
  - License: license.md
  - Code Reference: reference/
  - Contributing: contributing.md

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [ spark_instructor ]
  - section-index

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition