site_name: spark-instructor
repo_url: https://github.com/TJC-LP/spark-instructor
repo_name: TJC-LP/spark-instructor
site_author: Richie Caputo
edit_uri: ""

theme:
  name: "material"
  logo: assets/TJC_White_Logo.svg
  favicon: assets/TJC_280_Logo.svg
  font:
    text: "open-sans"
  palette:
    - scheme: default
      primary: "#012169"            # TJC Blue
      accent: "#307FE2"             # Highlight Blue
      background: "#FFFFFF"         # White background
      surface: "#D8DFE1"            # Gray tint for contrast
      on_primary: "#FFFFFF"         # White text on primary
      on_surface: "#262730"         # Near-black text color
  icon:
    logo: material/shimmer
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

nav:
  - Home: index.md
  - License: license.md
  - Code Reference: reference/
  - Contributing: contributing.md

plugins:
  - search
  - gen-files:
      scripts:
        - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [ spark_instructor ]
  - section-index

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - admonition

extra_css:
  - theme/extra.css
