name: Build and Test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.10', 3.11, 3.12 ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --extras anthropic --without databricks

    - name: Run lint script
      env:
        SAFETY_API_KEY: ${{ secrets.SAFETY_API_KEY }}
      run: poetry run lint

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}