name: Publish to PyPi

on:
  release:
    types: [published]

jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Build and publish
      run: |
        poetry build
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
        poetry publish
  deploy-docs:
    runs-on: ubuntu-latest
    needs:
      - publish-to-pypi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: poetry run mkdocs gh-deploy --force